### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by moCello** [dusk-network/piecrust#127]
#### Summary
Add a CHANGELOG

**Comment by HDauven** [comment]
This is resolved as both of the published crates in this repo (`piecrust` and `piecrust-uplink`) have a changelog since the first release:
[piecrust changelog](https://github.com/dusk-network/piecrust/blob/3774018d5ddc11aef0a5720f4b48eb44dc82508b/piecrust/CHANGELOG.md)
[piecrust-uplink changelog](https://github.com/dusk-network/piecrust/blob/3774018d5ddc11aef0a5720f4b48eb44dc82508b/piecrust-uplink/CHANGELOG.md)
