### ISSUE TITLE
push_callstack not storing module instances

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#162]
**Describe the bug**
looks like every time push_callstack is called, a new module instance is created as existing instance is not found in instance_map

**To Reproduce**
run `cargo t counter_read_write_simple` and observe that module instance with the same module id is created 3 times

**Expected behaviour**
Module instance for a given module id should only be crated once as instance_map should cache instances

**Logs/Screenshot**
instance result from s.instance(e34e2104783737e9e747230e388638e53457fc82769b5c925732f10e321fd6de is some=false)
new instance called for module_id=e34e2104783737e9e747230e388638e53457fc82769b5c925732f10e321fd6de
creating wasmer module - bytecode len=443
instance result from s.instance(e34e2104783737e9e747230e388638e53457fc82769b5c925732f10e321fd6de is some=false)
new instance called for module_id=e34e2104783737e9e747230e388638e53457fc82769b5c925732f10e321fd6de
creating wasmer module - bytecode len=443
instance result from s.instance(e34e2104783737e9e747230e388638e53457fc82769b5c925732f10e321fd6de is some=false)
new instance called for module_id=e34e2104783737e9e747230e388638e53457fc82769b5c925732f10e321fd6de
creating wasmer module - bytecode len=443

**Platform**
MacOS

**Context**
On every session.query and/or session.transact new instance is created, this needs to be fixed.

**Comment by ureeves** [comment]
Indeed. Currently, the instance - meaning the `wasmer::Instance` - is created once per each transaction/query sequence. This can for sure be optimized instantiate it once per `Session`, significantly reducing the compilation overhead.

The problem here, I think, is not the instantiation of `wasmer::Instance` per-se, but more the compilation of the bytecode being performed more than once - given that it is the more expensive operation. Perhaps we should store compiled bytecode on disk, and this operation would be less expensive.

I don't think this is a bug - given that no functionality of the VM is impacted - but more a performance issue.
