### ISSUE TITLE
Panics should propagate to the caller

### ISSUE THREAD

**Issue by ureeves** [dusk-network/piecrust#79]
#### Summary
When performing an inter-contract call, a panic occurring in the called module should inform the caller that the module panicked, as opposed to stopping the execution.

This ensures the calling module is able to handle panics of modules whose code it has no control over.

#### Possible solution design or implementation
One possible implementation is modifying the API offered to module writers in `uplink`, by changing the signature of the `query` and `transact` functions to allow for failure.

As an example, instead of
```rust
pub fn query<Arg, Ret>(mod_id: ModuleId, name: &str, arg: Arg) -> Ret
```
a query could return a `Result` instead:
```rust
pub fn query<Arg, Ret>(mod_id: ModuleId, name: &str, arg: Arg) -> Result<Ret, Error>
```
where the `Error` could be:
```rust
enum Error {
    Panic,
    // other variants possible
}
```

#### Additional context
This is a required feature, since it allows the transfer module downstream to properly charge gas, even for execution that "fail".

**Comment by ZER0** [comment]
To give additional context: this is coming from the need of having the transfer contract not panicking.

We have the transfer contract as entry point for all the other contract, so that we can pay the fees. However, if the contract called (let's say, the `stake`) panics, currently also the transfer contract (the caller) will panic too, and therefore the fees would never be paid – because the state will revert for the whole chain of calls.

So we should be able to knows when a contract panic in a icc, so that the caller could handle the situation: e.g. in the case of the transfer contract, he will recognize the contract panic and it will ensure the fees are paid, without panicking itself.

This mechanism could be generalized as @ureeves described, so any contracts can deal with the panicking of the contracts they call.

Of course if a icc panic, the contract's state up to that point needs to be reverted. However, the gas spent until the panic needs to be kept so that we can use it.

Some scenario.
Assuming the following call's tree:

```
- A (top call, transfer contract)
    - B (panicking)
        - C (not panicking)
```

The only state we keep is from the contract `A`, even if the call `C` was doing fine.

While with this tree:

```
- A (top call, transfer contract)
    - B (not panicking)
        - C (panicking)
```

The state we kept is from the contract `B`, that will deal with the contract `C`'s panic. Unless he decided to propagate the panic, but then we're in a similar situation as the first one.

If for any reason is the top contract to panic, then no state is kept at all.
